language: python
python: 3.6

install:
  - pip install -r requirements.txt

script:
  - sphinx-build -W . _build

after_success:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      export DATE=$(date '+%Y-%m-%d %T');
      ghp-import -m "Last update at $DATE" -b gh-pages _build;
      git config --global user.email "travis@travis-ci.org";
      git config --global user.name "TravisCI";
      git push -fq "https://$GH_TOKEN@github.com/nengo/enhancement_proposals.git" gh-pages;
    fi
